// Testando divisao com try catch

public class TestandoDivisao{
   public static void main(String[] args){
   int i = 0;
    try{
      i = i/2;
    } catch(ArithmeticException + e){
          System.out.println("Erro:" + e);
    }
    System.out.println("Resultado" + i);
    }
     
  }
